// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class Betslip
{
    public Guid Id { get; set; }

    public Guid Userid { get; set; }

    public bool Ispremium { get; set; }

    public int Likecount { get; set; }

    public int Commentcount { get; set; }

    public DateTime? Createdate { get; set; }

    public DateTime? Updatedate { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual User User { get; set; }
}