// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class City
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public Guid Countryid { get; set; }

    public DateTime? Createdate { get; set; }

    public DateTime? Updatedate { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}