// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class Country
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Countrycode { get; set; }

    public DateTime Createdate { get; set; }

    public DateTime? Updatedate { get; set; }

    public string Phoneregex { get; set; }

    public string Phonemask { get; set; }

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}