// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class Emailverification
{
    public Guid Id { get; set; }

    public Guid Userid { get; set; }

    public string Code { get; set; }

    public DateTime Expiresat { get; set; }

    public bool? Isused { get; set; }

    public DateTime? Createdate { get; set; }

    public virtual User User { get; set; }
}