// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class Referralreward
{
    public Guid Id { get; set; }

    public Guid Userid { get; set; }

    public Guid Referrerid { get; set; }

    public decimal Amount { get; set; }

    public DateTime? Createdate { get; set; }

    public DateTime? Updatedate { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual User Referrer { get; set; }

    public virtual User User { get; set; }
}