// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class Schedulerresult
{
    public Guid Id { get; set; }

    public string Jobkey { get; set; }

    public string Jobgroup { get; set; }

    public string Jobdescription { get; set; }

    public string Resultdetail { get; set; }

    public DateTime Startdate { get; set; }

    public DateTime Enddate { get; set; }

    public TimeSpan Workingtime { get; set; }

    public Guid? Userid { get; set; }
}