// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class Team
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Country { get; set; }

    public string Tags { get; set; }

    public DateTime Createdate { get; set; }

    public DateTime? Updatedate { get; set; }

    public bool? Isdeleted { get; set; }
}