// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerX.Domain.Entities;

public partial class User
{
    public Guid Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public DateOnly Birthdate { get; set; }

    public string Passwordhash { get; set; }

    public DateTime? Banenddate { get; set; }

    public Guid? Referraluserid { get; set; }

    public int Followercount { get; set; }

    public Guid Countryid { get; set; }

    public Guid Cityid { get; set; }

    public string Postalcode { get; set; }

    public string Address { get; set; }

    public string Phonenumber { get; set; }

    public string Avatarurl { get; set; }

    public DateTime Createdate { get; set; }

    public DateTime? Updatedate { get; set; }

    public bool Isdeleted { get; set; }

    public bool Isemailconfirmed { get; set; }

    public string Externalid { get; set; }

    public bool Isprofilecomplete { get; set; }

    public long Rowversion { get; set; }

    public decimal Balance { get; set; }

    public virtual ICollection<Auditlog> Auditlogs { get; set; } = new List<Auditlog>();

    public virtual ICollection<Betslip> Betslips { get; set; } = new List<Betslip>();

    public virtual City City { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual Country Country { get; set; }

    public virtual ICollection<Emailverification> Emailverifications { get; set; } = new List<Emailverification>();

    public virtual ICollection<User> InverseReferraluser { get; set; } = new List<User>();

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Referralreward> ReferralrewardReferrers { get; set; } = new List<Referralreward>();

    public virtual ICollection<Referralreward> ReferralrewardUsers { get; set; } = new List<Referralreward>();

    public virtual User Referraluser { get; set; }

    public virtual ICollection<Subscription> SubscriptionEditors { get; set; } = new List<Subscription>();

    public virtual ICollection<Subscription> SubscriptionSubscribers { get; set; } = new List<Subscription>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<User> Blockeds { get; set; } = new List<User>();

    public virtual ICollection<User> Blockers { get; set; } = new List<User>();

    public virtual ICollection<User> Followers { get; set; } = new List<User>();

    public virtual ICollection<User> Followings { get; set; } = new List<User>();
}