//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerX.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoccerX.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres girilmesi zorunludur..
        /// </summary>
        public static string Address_NotEmpty {
            get {
                return ResourceManager.GetString("Address_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı yasaklı durumda olduğunda yasak bitiş tarihi zorunludur..
        /// </summary>
        public static string BanEndDate_Required {
            get {
                return ResourceManager.GetString("BanEndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli bir e-posta girin..
        /// </summary>
        public static string Email_EmailAddress {
            get {
                return ResourceManager.GetString("Email_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta zorunlu..
        /// </summary>
        public static string Email_NotEmpty {
            get {
                return ResourceManager.GetString("Email_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablo&apos; da {0} Constraint hatası alındı.
        /// </summary>
        public static string error_database_tableconstraint {
            get {
                return ResourceManager.GetString("error_database_tableconstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre hatalı..
        /// </summary>
        public static string error_InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("error_InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin tarafından {0}. Tarihine kadar sisteme girişiniz askıya alındı.
        /// </summary>
        public static string error_userBanned {
            get {
                return ResourceManager.GetString("error_userBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} e-mail adresi sistemde başka bir kullanıcı tarafından kullanılmaktadır..
        /// </summary>
        public static string error_userEmailIsExist {
            get {
                return ResourceManager.GetString("error_userEmailIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kullanıcı adı sistemde başka bir kullanıcı tarafından kullanılmaktadır..
        /// </summary>
        public static string error_userNameIsExist {
            get {
                return ResourceManager.GetString("error_userNameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınızı giriniz..
        /// </summary>
        public static string Name_NotEmpty {
            get {
                return ResourceManager.GetString("Name_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az bir rakam içermeli..
        /// </summary>
        public static string Password_Digit {
            get {
                return ResourceManager.GetString("Password_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az 8 karakter olmalı..
        /// </summary>
        public static string Password_MinimumLength {
            get {
                return ResourceManager.GetString("Password_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre zorunlu..
        /// </summary>
        public static string Password_NotEmpty {
            get {
                return ResourceManager.GetString("Password_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az bir büyük harf içermeli..
        /// </summary>
        public static string Password_UppercaseLetter {
            get {
                return ResourceManager.GetString("Password_UppercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bilgisi zorunludur..
        /// </summary>
        public static string Phonenumber_NotEmpty {
            get {
                return ResourceManager.GetString("Phonenumber_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınızı giriniz..
        /// </summary>
        public static string Surname_NotEmpty {
            get {
                return ResourceManager.GetString("Surname_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az 3 karakter olmalı..
        /// </summary>
        public static string Username_MinimumLength {
            get {
                return ResourceManager.GetString("Username_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı zorunlu..
        /// </summary>
        public static string Username_NotEmpty {
            get {
                return ResourceManager.GetString("Username_NotEmpty", resourceCulture);
            }
        }
    }
}
